### ISSUE TITLE
doesn't work on redmine 9.2.0

### ISSUE THREAD

**Issue by olkobg** [ndl/wiki_external_filter#1]
Could you please investigate issue with redmine 9.2 and your plugin.
Here are script/about output:
About your application's environment
Ruby version              1.8.7 (i486-linux)
RubyGems version          1.3.5
Rack version              1.0
Rails version             2.3.5
Active Record version     2.3.5
Active Resource version   2.3.5
Action Mailer version     2.3.5
Active Support version    2.3.5
Application root          /var/www/railst
Environment               development
Database adapter          mysql
Database schema version   20091227112908

About your Redmine plugins
Redmine Wiki Extensions plugin   0.2.0
Redmine ezLibrarian plugin       0.1.1
Bulk Time Entry                  0.4.0
Wiki External Filter Plugin      0.0.1
Google Calendar Plugin           0.1.2
Messenger Plugin                 0.0.9
Timesheet Plugin                 0.5.0
Redmine Blogs plugin             0.0.3
Issue Due Date                   0.1.0
Customer plugin                  0.2.0
Charts Plugin                    0.0.14
Redmine Graphs plugin            0.1.0
Redmine Issues Group plugin      0.1.7

production.log: 

ActionView::TemplateError (undefined method `fragment_cache_store' for ActionController::Base:Class) on line #19 of vendor/plugins/wiki_external_filter/app/views/wiki_external_filter/_settings.html.erb:
16:   <p>
17:     Current cache settings are:<br/>
18:       ActionController::Base.cache_configured? = <%= h ActionController::Base.cache_configured? ? "true" : "false" %><br/>
19:       ActionController::Base.fragment_cache_store = <%= h ActionController::Base.fragment_cache_store.inspect %>
20:   </p>
21: </fieldset>

```
vendor/plugins/wiki_external_filter/app/views/wiki_external_filter/_settings.html.erb:19
app/views/settings/plugin.rhtml:6:in `_run_rhtml_app47views47settings47plugin46rhtml'
app/views/settings/plugin.rhtml:4:in `_run_rhtml_app47views47settings47plugin46rhtml'
passenger (2.2.9) lib/phusion_passenger/rack/request_handler.rb:92:in `process_request'
passenger (2.2.9) lib/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
passenger (2.2.9) lib/phusion_passenger/railz/application_spawner.rb:400:in `start_request_handler'
passenger (2.2.9) lib/phusion_passenger/railz/application_spawner.rb:351:in `handle_spawn_application'
passenger (2.2.9) lib/phusion_passenger/utils.rb:184:in `safe_fork'
passenger (2.2.9) lib/phusion_passenger/railz/application_spawner.rb:349:in `handle_spawn_application'
passenger (2.2.9) lib/phusion_passenger/abstract_server.rb:352:in `__send__'
passenger (2.2.9) lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
passenger (2.2.9) lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
passenger (2.2.9) lib/phusion_passenger/abstract_server.rb:163:in `start'
passenger (2.2.9) lib/phusion_passenger/railz/application_spawner.rb:209:in `start'
passenger (2.2.9) lib/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
passenger (2.2.9) lib/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
passenger (2.2.9) lib/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
passenger (2.2.9) lib/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
passenger (2.2.9) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
passenger (2.2.9) lib/phusion_passenger/spawn_manager.rb:255:in `spawn_rails_application'
passenger (2.2.9) lib/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
passenger (2.2.9) lib/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
passenger (2.2.9) lib/phusion_passenger/abstract_server.rb:352:in `__send__'
passenger (2.2.9) lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
passenger (2.2.9) lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
```

Rendering /var/www/railst/public/500.html (500 Internal Server Error)
Thanks in advance

**Comment by ndl** [comment]
Should work with last commit, thanks for reporting! Please reopen if any further problems.
